//
// Created by jamie on 11/13/22.
//

#ifndef TETRISCLONE_WINDOWCONSTANTS_H
#define TETRISCLONE_WINDOWCONSTANTS_H

#endif //TETRISCLONE_WINDOWCONSTANTS_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600